export const abbreviations = {
    "CHF": "Congestive Heart Failure (fluid buildup in the heart)",
    "EF": "Ejection Fraction (percentage of blood pumped out with each beat)",
    "ANA": "Antinuclear Antibody (immune proteins targeting body's own tissues)",
    "MCP": "Metacarpophalangeal (the knuckles where fingers meet the hand)",
    "AFB": "Acid-Fast Bacilli (bacteria type, often indicates tuberculosis)",
    "PCR": "Polymerase Chain Reaction (highly accurate genetic test)",
    "GDMT": "Guideline-Directed Medical Therapy (evidence-based heart medication regimen)",
    "SGLT2": "Sodium-Glucose Cotransporter 2 (medication class that helps kidneys clear sugar)",
    "HFrEF": "Heart Failure with Reduced Ejection Fraction (weak heart pumping capability)",
    "SLE": "Systemic Lupus Erythematosus (chronic autoimmune disease affecting multiple organs)",
    "dsDNA": "Double-stranded DNA antibody (specific marker for Lupus auto-immunity)",
    "BAL": "Bronchoalveolar Lavage (lung washing procedure to gather samples)",
    "CXR": "Chest X-Ray (imaging of chest structure and lungs)",
    "HIV": "Human Immunodeficiency Virus (immune system virus)",
    "ART": "Antiretroviral Therapy (standard medication combination for HIV)",
    "HTN": "Hypertension (high blood pressure condition)",
    "COPD": "Chronic Obstructive Pulmonary Disease (progressive lung inflammatory disease)",
    "DM": "Diabetes Mellitus (chronic high blood sugar condition)",
    "PCP": "Pneumocystis Pneumonia (serious opportunistic lung infection in immunocompromised hosts)",
    "BMP": "Basic Metabolic Panel (standard blood test for kidney function and electrolytes)",
    "A1c": "Hemoglobin A1c (average blood sugar level over the past 3 months)"
};
